# 开启自动更新
auto-update: false

# max-distance最大距离限制 100
# pushitem-tick 1 Tick=0.5秒 推送物品的时间
# grabitem-tick 1 Tick=0.5秒 抓取物品的时间
# required-power 抓取和推送分别每次网络电力消耗
# enable 是否启用模型 false true
# type 指定模型的类型 错误类型enable将会启用false
items:
  #网络链式推送器
  NE_CHAIN_PUSHER:
    max-distance: 32
    pushitem-tick: 6
    grabitem-tick: 12
    use-special-model:
      enable: false
  #网络链式推送器Plus
  NE_CHAIN_PUSHER_PLUS:
    max-distance: 64
    pushitem-tick: 6
    grabitem-tick: 12
    use-special-model:
      enable: false
  #网络链式抓取器
  NE_CHAIN_GRABBER:
    max-distance: 32
    pushitem-tick: 6
    grabitem-tick: 12
    use-special-model:
      enable: false
  #网络链式抓取器Plus
  NE_CHAIN_GRABBER_PLUS:
    max-distance: 64
    pushitem-tick: 6
    grabitem-tick: 12
    use-special-model:
      enable: false
  #网链调度器
  CHAIN_DISPATCHER:
    max-distance: 32
    pushitem-tick: 4
    grabitem-tick: 6
    required-power: 5000
    use-special-model:
      enable: false
  #网链调度器Plus
  CHAIN_DISPATCHER_PLUS:
    max-distance: 64
    pushitem-tick: 12
    grabitem-tick: 12
    required-power: 5000
    use-special-model:
      enable: false

  #高级网络链式推送器
  NE_ADVANCED_CHAING_PUSHER:
    max-distance: 32
    pushitem-tick: 6
    grabitem-tick: 12
    use-special-model:
      enable: false
  #高级网络链式推送器Plus
  NE_ADVANCED_CHAING_PUSHER_PLUS:
    max-distance: 64
    pushitem-tick: 6
    grabitem-tick: 12
    use-special-model:
      enable: false
  #高级网络链式抓取器
  NE_ADVANCED_CHAING_GRABBER:
    max-distance: 32
    pushitem-tick: 6
    grabitem-tick: 12
    use-special-model:
      enable: false
  #高级网络链式抓取器Plus
  NE_ADVANCED_CHAING_GRABBER_PLUS:
    max-distance: 64
    pushitem-tick: 6
    grabitem-tick: 12
    use-special-model:
      enable: false
  #高级网链调度器
  NE_ADVANCED_CHAIN_DISPATCHER:
    max-distance: 32
    pushitem-tick: 6
    grabitem-tick: 12
    required-power: 5000
    use-special-model:
      enable: false
  #高级网链调度器Plus
  NE_ADVANCED_CHAING_DISPATCHER_PLUS:
    max-distance: 64
    pushitem-tick: 4
    grabitem-tick: 12
    required-power: 5000
    use-special-model:
      enable: false



  # 链式传输器[推送]
  NTW_EXPANSION_LINE_TRANSFER_PUSHER:
    max-distance: 32
    pushitem-tick: 5
    use-special-model:
      enable: false
  # 链式传输器[抓取]
  NTW_EXPANSION_LINE_TRANSFER_GRABBER:
    max-distance: 32
    grabitem-tick: 12
    use-special-model:
      enable: false
  # 链式传输器
  NTW_EXPANSION_LINE_TRANSFER:
    max-distance: 32
    pushitem-tick: 5
    grabitem-tick: 12
    use-special-model:
      enable: false
  # 链式传输器Plus[推送]
  NTW_EXPANSION_LINE_TRANSFER_PLUS_PUSHER:
    max-distance: 32
    pushitem-tick: 5
    use-special-model:
      enable: false
  # 链式传输器Plus[抓取]
  NTW_EXPANSION_LINE_TRANSFER_PLUS_GRABBER:
    max-distance: 32
    grabitem-tick: 12
    use-special-model:
      enable: false
  # 链式传输器Plus
  NTW_EXPANSION_LINE_TRANSFER_PLUS:
    max-distance: 32
    pushitem-tick: 5
    grabitem-tick: 12
    required-power: 5000
    use-special-model:
      enable: false
  # 高级链式传输器[推送]
  NTW_EXPANSION_ADVANCED_LINE_TRANSFER_PUSHER:
    max-distance: 32
    pushitem-tick: 5
    use-special-model:
      enable: false
  # 高级链式传输器[抓取]
  NTW_EXPANSION_ADVANCED_LINE_TRANSFER_GRABBER:
    max-distance: 32
    grabitem-tick: 12
    use-special-model:
      enable: false
  # 高级链式传输器
  NTW_EXPANSION_ADVANCED_LINE_TRANSFER:
    max-distance: 32
    pushitem-tick: 5
    grabitem-tick: 12
    use-special-model:
      enable: false
  # 高级链式传输器Plus[推送]
  NTW_EXPANSION_ADVANCED_LINE_TRANSFER_PLUS_PUSHER:
    max-distance: 64
    pushitem-tick: 5
    use-special-model:
      enable: false
  # 高级链式传输器Plus[抓取]
  NTW_EXPANSION_ADVANCED_LINE_TRANSFER_PLUS_GRABBER:
    max-distance: 64
    grabitem-tick: 12
    use-special-model:
      enable: false
  # 高级链式传输器Plus
  NTW_EXPANSION_ADVANCED_LINE_TRANSFER_PLUS:
    max-distance: 64
    pushitem-tick: 5
    grabitem-tick: 12
    required-power: 5000
    use-special-model:
      enable: false
